# Generated by Django 3.0.6 on 2020-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(choices=[('', 'Choisissez...'), ('1', 'Paquet 1'), ('2', 'Paquet 2'), ('3', 'Paquet 3'), ('4', 'Paquet 4'), ('5', 'Paquet 5'), ('6', 'Paquet 6')], default='Non défini', max_length=1)),
                ('quantity', models.CharField(choices=[('', 'Choisissez...'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=1)),
                ('extra_needs', models.CharField(max_length=200)),
                ('validate', models.BooleanField()),
            ],
        ),
    ]