# Generated by Django 3.0.6 on 2020-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('address_1', models.CharField(max_length=80)),
                ('address_2', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('zip_code', models.CharField(max_length=80)),
                ('nbrpersonnes', models.IntegerField()),
                ('phonenumber', models.CharField(max_length=80)),
                ('profession', models.CharField(max_length=80)),
                ('check_me_out', models.BooleanField()),
            ],
        ),
    ]
